---
fastapi_app_dir: /opt/fastapi-tutorial
fastapi_project_name: FastAPI Tutorial
fastapi_api_version: 1.0.0
fastapi_host: 0.0.0.0
fastapi_port: 8000
fastapi_git_repo: https://github.com/dibanez/fastapi_tutorial.git
fastapi_git_branch: main
fastapi_db_name: fastapi_db
fastapi_db_user: fastapi
fastapi_db_password: fastapi_password
fastapi_python_packages:
  - python3
  - python3-pip
  - python3-venv
  - git
  - postgresql
  - postgresql-contrib
  - libpq-dev
