---
- name: Install nginx package
  ansible.builtin.package:
    name: nginx
    state: present
- name: Configure nginx.conf
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: "0644"
  notify: Reload nginx
- name: Configure security.conf
  ansible.builtin.template:
    src: security.conf.j2
    dest: /etc/nginx/conf.d/security.conf
    mode: "0644"
  notify: Reload nginx
- name: Enable and start nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
- name: Create document root directories for each site
  ansible.builtin.file:
    path: "{{ item.value.document_root }}"
    owner: www-data
    group: www-data
    mode: "0755"
    state: directory
  loop: "{{ nginx.sites | dict2items }}"
- name: Copy index.html files for each site
  ansible.builtin.copy:
    src: "{{ item.key.split('.')[0] }}/index.html"
    dest: "{{ item.value.document_root }}/index.html"
    owner: www-data
    group: www-data
    mode: "0644"
  loop: "{{ nginx.sites | dict2items }}"
