---
- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  listen: restart nginx
- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  listen: reload nginx
- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
  listen: restart fail2ban
- name: Reload sysctl
  ansible.builtin.command: sysctl -p
  register: sysctl_output
  changed_when: false
  listen: reload sysctl
- name: Restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted
  listen: restart ssh
