---
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
- name: Restart FastAPI service
  ansible.builtin.systemd:
    name: "{{ fastapi_service_name }}"
    state: restarted
